"""initial schema

Revision ID: 56f66b0b05e2
Revises: 
Create Date: 2026-09-18 01:52:22.561910
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '56f66b0b05e2'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forest_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('habitat_type', sa.String(length=120), nullable=True),
    sa.Column('area_hectares', sa.Float(), nullable=True),
    sa.Column('center_latitude', sa.Float(), nullable=False),
    sa.Column('center_longitude', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('boundary_geojson', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forest_zones'))
    )
    op.create_index(op.f('ix_forest_zones_code'), 'forest_zones', ['code'], unique=True)
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=160), nullable=False),
    sa.Column('scientific_name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.Enum('MAMMAL', 'BIRD', 'PLANT', 'REPTILE', 'AMPHIBIAN', 'INSECT', 'FUNGI', 'OTHER', name='speciescategory', native_enum=False, length=20), nullable=False),
    sa.Column('family', sa.String(length=120), nullable=True),
    sa.Column('genus', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('habitat', sa.Text(), nullable=True),
    sa.Column('conservation_status', sa.Enum('EX', 'EW', 'CR', 'EN', 'VU', 'NT', 'LC', 'DD', 'NE', name='conservationstatus', native_enum=False, length=4), nullable=False),
    sa.Column('is_location_sensitive', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('reference_url', sa.String(length=500), nullable=True),
    sa.Column('visual_traits', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('acoustic_signature', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('research_notes', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_species'))
    )
    op.create_index('ix_species_category_common_name', 'species', ['category', 'common_name'], unique=False)
    op.create_index(op.f('ix_species_common_name'), 'species', ['common_name'], unique=False)
    op.create_index(op.f('ix_species_family'), 'species', ['family'], unique=False)
    op.create_index(op.f('ix_species_scientific_name'), 'species', ['scientific_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'RESEARCHER', 'FOREST_OFFICER', 'EXPERT', 'VIEWER', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('organization', sa.String(length=160), nullable=True),
    sa.Column('expertise', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('anomaly_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('metric', sa.String(length=80), nullable=False),
    sa.Column('method', sa.Enum('ROBUST_Z', 'ISOLATION_FOREST', 'ENSEMBLE', name='anomalymethod', native_enum=False, length=24), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('baseline_spread', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['forest_zones.id'], name=op.f('fk_anomaly_scores_zone_id_forest_zones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anomaly_scores'))
    )
    op.create_index(op.f('ix_anomaly_scores_zone_id'), 'anomaly_scores', ['zone_id'], unique=False)
    op.create_index('ix_anomaly_scores_zone_window', 'anomaly_scores', ['zone_id', 'window_end'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('context', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity', 'entity_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.Enum('CAMERA_TRAP', 'ACOUSTIC_RECORDER', 'ENV_SENSOR', 'MULTI_SENSOR_NODE', name='devicekind', native_enum=False, length=24), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('firmware_version', sa.String(length=40), nullable=True),
    sa.Column('report_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingest_key_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['forest_zones.id'], name=op.f('fk_devices_zone_id_forest_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    op.create_index(op.f('ix_devices_device_code'), 'devices', ['device_code'], unique=True)
    op.create_index(op.f('ix_devices_zone_id'), 'devices', ['zone_id'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('research_question', sa.Text(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'RUNNING', 'COMPLETED', 'FAILED', name='experimentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('config', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_experiments_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments')),
    sa.UniqueConstraint('name', name=op.f('uq_experiments_name'))
    )
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('observation_type', sa.Enum('IMAGE', 'AUDIO', 'MULTIMODAL', 'FIELD_NOTE', 'CAMERA_TRAP', 'SENSOR', name='observationtype', native_enum=False, length=20), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_accuracy_m', sa.Float(), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('individual_count', sa.Integer(), nullable=True),
    sa.Column('conditions', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('ai_prediction', sa.String(length=160), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_model_version', sa.String(length=80), nullable=True),
    sa.Column('ai_predicted_species_id', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', 'CORRECTED', 'UNCERTAIN', name='verificationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('verified_species_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('ai_confidence IS NULL OR (ai_confidence >= 0 AND ai_confidence <= 1)', name=op.f('ck_observations_ai_confidence_range')),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90 AND latitude <= 90)', name=op.f('ck_observations_latitude_range')),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180 AND longitude <= 180)', name=op.f('ck_observations_longitude_range')),
    sa.ForeignKeyConstraint(['ai_predicted_species_id'], ['species.id'], name=op.f('fk_observations_ai_predicted_species_id_species'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['researcher_id'], ['users.id'], name=op.f('fk_observations_researcher_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], name=op.f('fk_observations_species_id_species'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_species_id'], ['species.id'], name=op.f('fk_observations_verified_species_id_species'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['forest_zones.id'], name=op.f('fk_observations_zone_id_forest_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observations'))
    )
    op.create_index('ix_observations_lat_lon', 'observations', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_observations_observed_at'), 'observations', ['observed_at'], unique=False)
    op.create_index('ix_observations_observed_at_zone', 'observations', ['observed_at', 'zone_id'], unique=False)
    op.create_index(op.f('ix_observations_researcher_id'), 'observations', ['researcher_id'], unique=False)
    op.create_index(op.f('ix_observations_species_id'), 'observations', ['species_id'], unique=False)
    op.create_index('ix_observations_status_species', 'observations', ['verification_status', 'species_id'], unique=False)
    op.create_index(op.f('ix_observations_verification_status'), 'observations', ['verification_status'], unique=False)
    op.create_index(op.f('ix_observations_zone_id'), 'observations', ['zone_id'], unique=False)
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token_type', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_revoked_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revoked_tokens'))
    )
    op.create_index('ix_revoked_tokens_expires_at', 'revoked_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=True)
    op.create_table('ai_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=True),
    sa.Column('modality', sa.Enum('IMAGE', 'AUDIO', 'SENSOR', 'FUSED', name='modality', native_enum=False, length=12), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('predicted_species_id', sa.Integer(), nullable=True),
    sa.Column('predicted_label', sa.String(length=160), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_uncertain', sa.Boolean(), nullable=False),
    sa.Column('top_k', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('detections', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('diagnostics', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_ai_predictions_confidence_range')),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], name=op.f('fk_ai_predictions_observation_id_observations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['predicted_species_id'], ['species.id'], name=op.f('fk_ai_predictions_predicted_species_id_species'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_predictions'))
    )
    op.create_index('ix_ai_predictions_modality_model', 'ai_predictions', ['modality', 'model_name'], unique=False)
    op.create_index(op.f('ix_ai_predictions_observation_id'), 'ai_predictions', ['observation_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('BIODIVERSITY_ANOMALY', 'ACOUSTIC_ANOMALY', 'SENSOR_MALFUNCTION', 'DEVICE_OFFLINE', 'DATA_GAP', 'THREATENED_SPECIES_DETECTION', name='alertkind', native_enum=False, length=32), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', name='alertseverity', native_enum=False, length=12), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'RESOLVED', 'DISMISSED', name='alertstatus', native_enum=False, length=16), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('anomaly_score_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('candidate_causes', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_by_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('confirmed_cause', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], name=op.f('fk_alerts_acknowledged_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['anomaly_score_id'], ['anomaly_scores.id'], name=op.f('fk_alerts_anomaly_score_id_anomaly_scores'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_alerts_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['forest_zones.id'], name=op.f('fk_alerts_zone_id_forest_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_status_detected', 'alerts', ['status', 'detected_at'], unique=False)
    op.create_index(op.f('ix_alerts_zone_id'), 'alerts', ['zone_id'], unique=False)
    op.create_table('experiment_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('variant', sa.String(length=60), nullable=False),
    sa.Column('metrics', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('per_class_metrics', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('confusion_matrix', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_experiment_runs_experiment_id_experiments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_runs'))
    )
    op.create_index(op.f('ix_experiment_runs_experiment_id'), 'experiment_runs', ['experiment_id'], unique=False)
    op.create_table('expert_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('CONFIRM', 'REJECT', 'CORRECT', 'UNCERTAIN', name='verificationdecision', native_enum=False, length=20), nullable=False),
    sa.Column('corrected_species_id', sa.Integer(), nullable=True),
    sa.Column('previous_species_id', sa.Integer(), nullable=True),
    sa.Column('ai_predicted_label', sa.String(length=160), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corrected_species_id'], ['species.id'], name=op.f('fk_expert_verifications_corrected_species_id_species'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expert_id'], ['users.id'], name=op.f('fk_expert_verifications_expert_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], name=op.f('fk_expert_verifications_observation_id_observations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_species_id'], ['species.id'], name=op.f('fk_expert_verifications_previous_species_id_species'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expert_verifications'))
    )
    op.create_index(op.f('ix_expert_verifications_expert_id'), 'expert_verifications', ['expert_id'], unique=False)
    op.create_index(op.f('ix_expert_verifications_observation_id'), 'expert_verifications', ['observation_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('IMAGE', 'AUDIO', 'SPECTROGRAM', 'DOCUMENT', name='mediakind', native_enum=False, length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('public_url', sa.String(length=600), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], name=op.f('fk_media_assets_observation_id_observations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets'))
    )
    op.create_index(op.f('ix_media_assets_checksum'), 'media_assets', ['checksum'], unique=False)
    op.create_index(op.f('ix_media_assets_observation_id'), 'media_assets', ['observation_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('illuminance_lux', sa.Float(), nullable=True),
    sa.Column('soil_moisture_pct', sa.Float(), nullable=True),
    sa.Column('sound_level_db', sa.Float(), nullable=True),
    sa.Column('motion_events', sa.Integer(), nullable=True),
    sa.Column('battery_volts', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON(none_as_null=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_sensor_readings_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['forest_zones.id'], name=op.f('fk_sensor_readings_zone_id_forest_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensor_readings'))
    )
    op.create_index(op.f('ix_sensor_readings_device_id'), 'sensor_readings', ['device_id'], unique=False)
    op.create_index('ix_sensor_readings_device_recorded', 'sensor_readings', ['device_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_sensor_readings_recorded_at'), 'sensor_readings', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_sensor_readings_zone_id'), 'sensor_readings', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_zone_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_recorded_at'), table_name='sensor_readings')
    op.drop_index('ix_sensor_readings_device_recorded', table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_device_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_media_assets_observation_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_checksum'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_expert_verifications_observation_id'), table_name='expert_verifications')
    op.drop_index(op.f('ix_expert_verifications_expert_id'), table_name='expert_verifications')
    op.drop_table('expert_verifications')
    op.drop_index(op.f('ix_experiment_runs_experiment_id'), table_name='experiment_runs')
    op.drop_table('experiment_runs')
    op.drop_index(op.f('ix_alerts_zone_id'), table_name='alerts')
    op.drop_index('ix_alerts_status_detected', table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_ai_predictions_observation_id'), table_name='ai_predictions')
    op.drop_index('ix_ai_predictions_modality_model', table_name='ai_predictions')
    op.drop_table('ai_predictions')
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.drop_index('ix_revoked_tokens_expires_at', table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_index(op.f('ix_observations_zone_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_verification_status'), table_name='observations')
    op.drop_index('ix_observations_status_species', table_name='observations')
    op.drop_index(op.f('ix_observations_species_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_researcher_id'), table_name='observations')
    op.drop_index('ix_observations_observed_at_zone', table_name='observations')
    op.drop_index(op.f('ix_observations_observed_at'), table_name='observations')
    op.drop_index('ix_observations_lat_lon', table_name='observations')
    op.drop_table('observations')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_devices_zone_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_code'), table_name='devices')
    op.drop_table('devices')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_anomaly_scores_zone_window', table_name='anomaly_scores')
    op.drop_index(op.f('ix_anomaly_scores_zone_id'), table_name='anomaly_scores')
    op.drop_table('anomaly_scores')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_species_scientific_name'), table_name='species')
    op.drop_index(op.f('ix_species_family'), table_name='species')
    op.drop_index(op.f('ix_species_common_name'), table_name='species')
    op.drop_index('ix_species_category_common_name', table_name='species')
    op.drop_table('species')
    op.drop_index(op.f('ix_forest_zones_code'), table_name='forest_zones')
    op.drop_table('forest_zones')
    # ### end Alembic commands ###
